### ISSUE TITLE
Uncaught TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by voltuer** [dafcoe/vue-collapsible-panel#12]
Hi, I'm trying to use this and followed instructions, tried adding into main.js or the Vue file, but same problem.

My HTML:

```
      <vue-collapsible-panel-group>
        <vue-collapsible-panel>
          <template #title>
            Panel A Title
          </template>
          <template #content>
            Panel A Content
          </template>
        </vue-collapsible-panel>
        <vue-collapsible-panel>
          <template #title>
            Panel B Title
          </template>
          <template #content>
            Panel B Content
          </template>
        </vue-collapsible-panel>
      </vue-collapsible-panel-group>
```
I keep getting
```
vue-collapsible-panel.common.js?9adf:3531 Uncaught TypeError: Object(...) is not a function
    at Module.fb15 (vue-collapsible-panel.common.js?9adf:3531)
    at __webpack_require__ (vue-collapsible-panel.common.js?9adf:21)
    at eval (vue-collapsible-panel.common.js?9adf:85)
    at eval (vue-collapsible-panel.common.js?9adf:88)
    at Object../node_modules/@dafcoe/vue-collapsible-panel/dist/vue-collapsible-panel.common.js (vendors~app.js:56)
    at __webpack_require__ (app.js:854)
    at fn (app.js:151)
    at eval (main.js:66)
    at Module../src/main.js (app.js:1843)
    at __webpack_require__ (app.js:854)
```
The referenced line has this:
![image](https://user-images.githubusercontent.com/197329/113740088-b062ef00-9700-11eb-9de2-62c8d206c48f.png)

**Comment by dafcoe** [comment]
Hi @tr4g,

Apparently you're using it the right way. Can you show more code, or at least where you import the component?

**Comment by gbkwiatt** [comment]
Same here, I've imported it locally in component. but it also doesn't work when registered globally.

**Comment by dafcoe** [comment]
Hi @gbkwiatt,

Can you share the code where you're registering it?

**Comment by vvnsrzn** [comment]
I have the same problem with Nuxt.

`plugins/accordion.client.js`

import Vue from 'vue'
import VueCollapsiblePanel from '@dafcoe/vue-collapsible-panel'
Vue.use(VueCollapsiblePanel)

`nuxt.config.js`
...
 plugins: [''~/plugins/accordion.client.js'],
...
