### ISSUE TITLE
How to override css variables

### ISSUE THREAD

**Issue by jhob101** [dafcoe/vue-collapsible-panel#13]
In the documentation is says "For granular control over the colors, the following css variables can be overridden:"

How is this done?

I've tried:

```
<style>
:root {
  --base-color: #64ADF0;
  --border-color: #64ADF0;
  --bg-color-header: #64ADF0;
  --bg-color-header-hover: #64ADF0;
  --bg-color-header-active: #64ADF0;
  --bg-color-body: #64ADF0;
}
</style>
```

in App.vue but that didn't work. Am I missing something?

Also setting the base-color has unusual results:

`<vue-collapsible-panel-group accordion base-color="#345345">`

results in a header color of #defdef

`<vue-collapsible-panel-group accordion base-color="#aaaaaa">`

results in a header color of #ffffff, as do most other hex codes I've tried.

This is in a vue3 project if that's significant.

**Comment by jhob101** [comment]
So I just worked out that I can override them like this:

```
div.vcpg {
  --base-color: #64ADF0 !important;
  --border-color: #64ADF0 !important;
  --bg-color-header: #64ADF0 !important;
  --bg-color-header-hover: #64ADF0 !important;
  --bg-color-header-active: #64ADF0 !important;
  --bg-color-body: #64ADF0 !important;
}
```

Is there a neater or preferred way of doing this?

**Comment by dafcoe** [comment]
Hi @jhob101,

So far, there's no other way to override the css vars without making use of `!important`.


Regarding the "unusual results" of `base-color`, they're lighter/darker color variants based on base-color.
