### ISSUE TITLE
Multiple panels opening by ref

### ISSUE THREAD

**Issue by jhob101** [dafcoe/vue-collapsible-panel#15]
I have an intermittent and slightly random bug.  On each panel I have ref so that I can toggle its visibility:

```
<vue-collapsible-panel-group accordion>
      <vue-collapsible-panel :expanded="true" ref="panel1">
        <template #title>
          Quote Info
        </template>
        <template #content>
          <h3>Service</h3>
        </template>
      </vue-collapsible-panel>
      <vue-collapsible-panel :expanded="false" ref="panel2">
        <template #title>
          Options
        </template>
        <template #content>
          <h3>Protection</h3>
        </template>
      </vue-collapsible-panel>
<vue-collapsible-panel :expanded="false" ref="panel3">
        <template #title>
          Delivery
        </template>
        <template #content>
          <h3>Address</h3>
        </template>
      </vue-collapsible-panel>
</vue-collapsible-panel-group>
```

And then I have the following method to control visibility:

```
setOpenPanel(current_page) {
      this.$refs['panel' + current_page].toggle();
},
```

But when this is triggered sometimes 2 panels, one of which does not correspond to `current_page` will open.  This is seemingly random and can vary between dev and build environments. 

This is how it looks in the html: https://bit.ly/3h5b660

I'm as sure as I can be that my code is doing what it should be doing and not calling `setOpenPanel` multiple times or with incorrect data so I think it must be a bug within this component.

Any ideas?

**Comment by swoga** [comment]
Are you using version 0.2.0?
I also had a similar problem (#14) with older versions.

**Comment by jhob101** [comment]
I had updated from npm previously but it looks like it might still have been on the old version.  Just updated again and made sure it's on 0.2.0 and so far it seems to be working correctly. Thanks!

**Comment by dafcoe** [comment]
Coll guys.
I'll close this issue then.
